
CC_FLAGS= $(CFLAGS) $(U_INT)
LINT_FLAGS= $(LINTFLAGS) 

all: ../lib/libmisc.a 
all: debug.o

!library libmisc.a strlib.c
!object debug.o debug.c

../lib/libmisc.a: libmisc.a
	rm -f ../lib/libmisc.a 
	ln -s ../common/libmisc.a ../lib/libmisc.a
	$(RANLIB) ../lib/libmisc.a

